language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pylint_runner
script:
- nosetests -v --with-coverage
- pylint_runner
after_success:
- coveralls