language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests -v --with-coverage
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Master_Odin
  password:
    secure: excHXeFQRgQTC8cWuZvhRhdrNehCj3dgqORcQ8LgBQmn35yJT3gsFP4wdB7FYhDex2ir6PlQmz4gVOwSOaX5jHblhUHMlmJoJXKwRY29WZ/oqDjBZ1wmmSrp+J20Dl+YRBB4MTWtRCgvcCkZyget8RuEl3h42zyvuno6uJJQm/0=
  on:
    repo: MasterOdin/forseti
    python: 3.3
